server:
  port: 8002

spring:
  application:
    name: spring-config-client
#  cloud:
#    config:
#      enabled: true
#      discovery:
#        service-id: spring-config-server

management:
  security:
    enabled: false

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:1111/eureka/
#注释部分必须放在bootstrap文件中


