server:
  port: 8002

spring:
  application:
    name: spring-config-client
  rabbitmq:
    host: 192.168.0.6
    port: 5672
    username: admin
    password: 123456

management:
  security:
    enabled: false



    #  cloud:
    #    config:
    #      enabled: true
    #      discovery:
    #        service-id: spring-config-server
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:1111/eureka/
#注释部分必须放在bootstrap文件中


