server:
  port: 8001
spring:
  application:
    name: spring-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/bxguo/springCloudDemo/    # 配置git仓库的地址
          search-paths: repo-config                             # git仓库地址下的相对地址，可以配置多个，用,分割。
          username:                                              # git仓库的账号
          password:                                             # git仓库的密码

  ## 一般guest账号制作mq控台登录使用
  rabbitmq:
    host: 192.168.200.115   #地址写的是本机的外网ip
    port: 5672
    username: admin
    password: 123456

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/

management:
  security:
    enabled: false